# Generated by Django 5.1.1 on 2024-10-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='city',
            new_name='Citie',
        ),
        migrations.RenameField(
            model_name='citie',
            old_name='city',
            new_name='city_name',
        ),
    ]
